# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/viacao_calango
spring.datasource.username=postgres
spring.datasource.password=senha123

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Parametros de Precificacao da Viacao Calango
calango.precificacao.dias-antecedencia=30
calango.precificacao.desconto-antecedencia=0.15
calango.precificacao.desconto-trajeto-completo=0.10
calango.precificacao.fator-leito=1.5
calango.precificacao.fator-executivo=1.2

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html